spring:
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  application:
    name: spring-ai-01
  ai:
    dashscope:
      api-key: API_KEY
      chat:
        options:
          model: qwen-max
#    openai:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: qwen-max
#          temperature: 0.8
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itheima?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.springai01.entity.po

logging:
  level:
    org.springframework.ai: debug
    com.example.springai01: debug
